### ISSUE TITLE
[v6.9.1] [android 7.0] setUserNotificationsEnabled doesn't prompt dialog box to user

### ISSUE THREAD

**Issue by MaxInMoon** [urbanairship/phonegap-ua-push#195] opened 2017-09-18 21:40 UTC
### **Bug**

`setUserNotificationsEnabled` only prompt the dialog box on iOS, but not on Android, however the success callback is well executed.

```javascript
UAirship.setUserNotificationsEnabled(true, function(enabled) {
  // callback 
});
```

### **More infos**

The app can receive push events while opened or paused in background, but **won't receive any push if closed**.

### **Versions**

UA: 6.9.1
Android: 7.0
cordova: 7.0.1
android: 6.2.3

**Comment by rlepinski** [comment] 2017-09-18 21:56
@MaxInMoon No permission is required to post notifications on Android.

**Comment by MaxInMoon** [comment] 2017-09-18 22:02
@rlepinski thanks! But I'm not able to receive a push when the app is closed.. do you have an idea?

**Comment by rlepinski** [comment] 2017-09-18 22:05
@MaxInMoon When the app is closed you are unable to see notifications or get the callback? If you are force closing the app or using another app to close it, it will prevent android devices from showing notifications.

**Comment by MaxInMoon** [comment] 2017-09-18 22:08
@rlepinski I just close the app as usual, with a swipe in the view where all opened apps are

**Comment by rlepinski** [comment] 2017-09-18 22:10
@MaxInMoon The notification does not display in that case? Or are you not receiving the callback?

**Comment by MaxInMoon** [comment] 2017-09-18 22:11
@rlepinski nothing at all, the notification does not display

**Comment by rlepinski** [comment] 2017-09-18 22:15
That is not the expected behavior, nor should it happen especially on Android. Double check that you are not disabling user notifications when you background the application. Try it on another device. To further help with this issue we will need android log outputs when you are receiving the notification. If you need any other help please contact support.

**Comment by MaxInMoon** [comment] 2017-09-18 22:16
@rlepinski thanks, I'll try on an other device soon, and investigate a little bit more

**Comment by MaxInMoon** [comment] 2017-09-20 21:53
@rlepinski the problem doesn't appear on Android 5.1..

The problem seems to be related with the Nougat management of "closing apps". From this [comment](https://stackoverflow.com/a/39505298/5832547):
> There are also devices where even if the app is still just simply swiped away, even though it's not force closed, the device itself is preventing it from receiving messages.

I even found a [fix](http://itechify.com/2016/02/01/how-to-fix-missing-push-notifications-on-huawei-smartphones/) for Huawei devices:
> - Download and install Quick Sync Settings from Google Play Store on your Huawei Phone.
> - Go to Settings -> Accounts -> Google -> Enable App-data Sync.Now Whatsapp, Facebook, Hangout and all other application’s push notifications will work even when the app is closed.

So that's the conclusion?

**Comment by rlepinski** [comment] 2017-09-20 22:30
@MaxInMoon That Huawei issue is actually a feature for that device. Its at the OS level and there does not appear to be anything an app can do to be whitelisted automatically. Nougat by default does not force this behavior, so majority of phones will not have this issue. 

The protected app list feature for Huawei seems to only whitelist some messaging apps automatically but everything else needs to be manually added by the user. The best thing you can do for now is to detect the manufacturer and instruct the user on the first run to whitelist the application.

We are currently investigating solutions to these devices, but due to this being an OS level "feature", I am not sure that we can provide a solution other then making it easier to instruct the user to whitelist the app manually.

**Closed** 2017-11-20 18:14 UTC
