### ISSUE TITLE
Empty push object from getLaunchNotification (Android/Phonegap)

### ISSUE THREAD

**Issue by jdjodrey** [urbanairship/phonegap-ua-push#103] opened 2016-04-12 13:49 UTC
On Android using Phonegap, when the application is launched because of a tap on a push notification, the getLaunchNotification method is always returning an empty push object. We are doing the following:

```
UAirship.getLaunchNotification(false, 
  function(push) { 
    alert(JSON.stringify(push)); 
  } 
);
```

There are two place where we are checking if the app was launched by an notification:

1. the app starts (onDeviceReady) 
2. on resume event (onResume)

Tapping a notification push launches the app and the alert fires showing "{ }". On iOS however, the push contains a message, our extras, etc. We're using the examples from the sample app and docs.

In our config.xml we're using:
`<gap:plugin name="urbanairship-cordova" source="npm" version="5.0.1" />`

**Comment by rlepinski** [comment] 2016-04-12 16:51
I was unable to reproduce the issue. I modified the sample to alert on the message object:

![device-2016-04-12-094857](https://cloud.githubusercontent.com/assets/3967591/14468311/efe02d86-0093-11e6-8031-11044c4798ea.png)


The first parameter of getLaunchNotification is a flag to tell the plugin to clear the notification. Is getLaunchNotification(true, ..) getting called before you are attempting to get the notification? Could you post the full index.html ?

**Comment by jdjodrey** [comment] 2016-04-12 19:26
All I've edited in index.html is updated the console.logs in onLaunchedFromPush to alerts. Otherwise it's unchanged.

![ua-push-launch](https://cloud.githubusercontent.com/assets/6324733/14472726/7762aa30-00c2-11e6-9a7d-2801d842bef1.png)


This is on a Samsung Galaxy S5 running Android 5.0

**Comment by jdjodrey** [comment] 2016-04-12 20:14
Updating our phonegap-version to cli-6.0.0 fixed this issue for me.

We were previously on cli-5.2.0 and were unable to get this plugin to work.

**Comment by rlepinski** [comment] 2016-04-12 20:51
@jdjodrey So its incompatible with cli-5.2.0? Any other errors you could point us to?

**Comment by jdjodrey** [comment] 2016-04-12 21:15
It seems that way, yes. There was no other indication of any errors, which is why it took us a while to even suspect the phonegap version.

**Comment by rlepinski** [comment] 2016-04-20 23:41
I was unable to reproduce it using an older cli... not sure whats going on here. I wonder if by updating your cli you cleared some internal build cache? 

Going to close it for now and if anyone else reports this issue I will add a note to the README.

**Closed by rlepinski** 2016-04-20 23:41 UTC
