### ISSUE TITLE
Not able to get urbanairship.notification_opened event when app is closed/killed

### ISSUE THREAD

**Issue by OmKessarwani** [urbanairship/phonegap-ua-push#179] opened 2017-03-29 11:23 UTC
when app is closed Not able to get urbanairship.notification_opened event, I need to get value from extra object for navigation to respective module of application.

**Comment by rlepinski** [comment] 2017-03-29 15:18
Could you provide more details about the issue? 

What plugin version, cordova version, and platform?

**Comment by OmKessarwani** [comment] 2017-03-29 18:28
Well not sure about plug-in version I had added it one month back,
Cordova version : 6.4.0
Platform : iOS

**Comment by rlepinski** [comment] 2017-03-29 22:02
@OmKessarwani Could you post the output of `cordova platform` and `cordova plugin`. Run each command in your projects root directory.

**Comment by OmKessarwani** [comment] 2017-03-30 07:21
@rlepinski  please find details below

1) cordova platform :-
Installed platforms:
  ios 4.3.1

2) cordova plugins :-
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-google-analytics 1.5.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-ext 0.10.4 "Cordova sqlite storage plugin with extras"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
**urbanairship-cordova 6.6.0 "Urban Airship"**

**Comment by rlepinski** [comment] 2017-04-03 16:55
@OmKessarwani Quick status update. I am trying to reproduce the issue right now.

**Comment by rlepinski** [comment] 2017-04-03 19:59
@OmKessarwani I am unable to reproduce your issue. I always receive the urbanairship.notification_opened event even if the device is killed. Tested on an iOS 10 device. Where are you setting up your listeners?

**Comment by OmKessarwani** [comment] 2017-04-04 07:24
@rlepinski, even now I'm not able to get event from when app is closed,
I'm using angular.js and I have added listeners in run.js.
steps in which I'm not getting above event are below.
1) App is killed (not available in background)
2) Received notification 
3) clicked on notification, now in my code I should get _urbanairship.notification_opened_, but not able  to get that.

**Comment by rlepinski** [comment] 2017-04-04 18:19
@OmKessarwani I did the same steps with the sample we provide, but was able to receive the event. Could provide a simple sample project that reproduces the issue? I think it might be in angular usage and not this plugin.

**Comment by OmKessarwani** [comment] 2017-04-05 07:28
@rlepinski Can you Please share your sample code which you are testing and able to get _urbanairship.notification_opened_ event.

**Comment by rlepinski** [comment] 2017-04-05 18:21
@OmKessarwani https://github.com/urbanairship/phonegap-ua-push/tree/master/Example

**Comment by OmKessarwani** [comment] 2017-04-06 10:58
@rlepinski 

1) With your sample code I was able to get urbanairship.notification_opened event, not sure why it is not working with angular.

2) Does urbanairship cordova platform provide support to lower iOS versions,
My code works perfectly on iOS 10 but when I tried to test it on iOS version 9.2.1 but it didn't worked.

**Comment by rlepinski** [comment] 2017-04-06 16:02
@OmKessarwani Yep, it should work on 9.2.1 and even 8.x. I do not have an iOS 9 device in front of me today, but I can confirm the sample tomorrow, unless you can?

**Comment by ralepinski** [comment] 2017-04-07 16:43
@OmKessarwani The sample is working on iOS 9. The plugin registers a listener in the JS layer on the device ready event - https://github.com/urbanairship/phonegap-ua-push/blob/master/www/UrbanAirship.js#L136. The native layer will store the notification_open until the listener is bound - https://github.com/urbanairship/phonegap-ua-push/blob/master/src/ios/UAirshipPlugin.m#L725

**Comment by rlepinski** [comment] 2017-04-07 16:44
@OmKessarwani The sample is working on iOS 9.

The plugin registers a listener in the JS layer on the device ready event - https://github.com/urbanairship/phonegap-ua-push/blob/master/www/UrbanAirship.js#L136. The native layer will store the notification_open until the listener is bound - https://github.com/urbanairship/phonegap-ua-push/blob/master/src/ios/UAirshipPlugin.m#L725

I am not sure what the issue is here. If you can provide a sample that shows the issue I might be able to help. For now I am going to close this issue as not reproducible.

**Closed by rlepinski** 2017-04-07 16:44 UTC
